# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "uas" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-a6074c99-c7c5-43a6-b15b-8d64317ab374";
      fsType = "xfs";
    };

    "/boot" = { 
      device = "/dev/disk/by-uuid/B8B7-26F4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    "/mnt/dev-disk" = {
      device = "/dev/disk/by-uuid/CA5E410B5E40F22D";
      fsType = "ntfs-3g";
      options = [ "uid=1000" "gid=100" ];
    };

    "/mnt/backup-disk" = {
      device = "/dev/disk/by-uuid/1ACEC9B8CEC98D07";
      fsType = "ntfs-3g";
      options = [ "uid=1000" "gid=100" ];
    };

    "/mnt/winders" = {
      device = "/dev/disk/by-uuid/D250EE2650EE1151";
      fsType = "ntfs-3g";
      options = [ "uid=1000" "gid=100" ];
    };

    /* For some Reason Clause does not work with skills in linux with symlinks like it does in WSL
    it some sort of directory protection to stop skills from re-Writing themselves while they are running.
    this fundamentally breaks the workflow. THis does not prevent that protection from working but prevents 
    the claude link startup check failing because the directory exists in two places via the link. */

    "/home/setkeh/.claude/skills" = {
      device = "/home/setkeh/SecondMind/AIOS/Skills";
      fsType = "none";
      options = [ "bind" ];
    };
  };

  boot.initrd.luks.devices."luks-a6074c99-c7c5-43a6-b15b-8d64317ab374".device = "/dev/disk/by-uuid/a6074c99-c7c5-43a6-b15b-8d64317ab374";

  swapDevices = [{
    device = "/dev/disk/by-partuuid/dd090197-b8da-4702-ab8a-a24fdb7149a8";
    randomEncryption.enable = true;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
